name: build

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "package*"
      - "**/build.yml"
  workflow_dispatch:
  pull_request_target:
    types: [labeled]

jobs:
  run:
    name: build
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.event == 'push' }} || ${{ github.event.event ==
      'workflow_dispatch' }} ||
      contains(github.event.pull_request.labels.*.name, 'wait-to-build')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Setup package
        run: yarn install

      - name: Bump version
        run: |
          yarn standard-version --skip.changelog --skip.commit --skip.tag

      - name: Generate name for artifact
        uses: actions/github-script@v3.1.0
        id: version
        with:
          result-encoding: string
          script: |
            core.setOutput('repo', context.repo.repo);
            core.setOutput('beta', process.env.GITHUB_SHA.slice(0,7));

      - name: Edit version for building
        run: |
          sed -r 's/"version": "(.*)"/"version": "\1-${{steps.version.outputs.beta}}"/' -i package.json

      - name: Build artifact
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{steps.version.outputs.repo}}-${{steps.version.outputs.beta}}.vsix
          path: "*.vsix"
