name: build

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "package*"
      - "**/build.yml"

jobs:
  run:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup nodejs
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Setup package
        run: yarn install

      - name: Generate name for artifact
        uses: actions/github-script@v3.1.0
        id: version
        with:
          result-encoding: string
          script: |
            core.setOutput('repo', context.repo.repo);
            core.setOutput('bate', process.env.GITHUB_SHA.slice(0,7));

      - name: Build artifact
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{steps.version.outputs.repo}}-${{steps.version.outputs.bate}}.vsix
          path: "*.vsix"
