name: build

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "package*"
      - "**/build.yml"
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: Build beta extension
    runs-on: ubuntu-latest
    if: >
      ${{ github.event_name == 'push' }} || ${{ github.event_name ==
      'workflow_dispatch' }} ||
      contains(github.event.pull_request.labels.*.name, 'wait-to-build')
    outputs:
      extension_name: ${{steps.version.outputs.repo}}-${{steps.version.outputs.beta}}.vsix
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Setup package
        run: yarn install

      - name: Bump version
        run: |
          yarn standard-version --skip.changelog --skip.commit --skip.tag

      - name: Generate name for artifact
        uses: actions/github-script@v3.1.0
        id: version
        with:
          result-encoding: string
          script: |
            core.setOutput('repo', context.repo.repo);
            core.setOutput('beta', process.env.GITHUB_SHA.slice(0,7));

      - name: Edit version for building
        run: |
          sed -r 's/"version": "(.*)"/"version": "\1-${{steps.version.outputs.beta}}"/' -i package.json

      - name: Build artifact
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{steps.version.outputs.repo}}-${{steps.version.outputs.beta}}.vsix
          path: "*.vsix"

  output:
    name: Output PR information
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'pull_request' }}
    steps:
      - name: Generate PR number and label name
        run: |
          mkdir -p ./pr
          printf ${{ github.event.number }} > ./pr/NR
          printf 'wait-to-build' > ./pr/label

      - name: Generate PR comment if success
        if: ${{ needs.build.result == 'success' }}
        env:
          url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}#artifacts
          name: ${{ needs.build.outputs.extension_name }}
        run: |
          printf "The beta extension of this pull has been built in the workflow! 🎉\n" >> ./pr/comment
          printf "Download \`${{ env.name }}\` " >> ./pr/comment
          printf "in [artifacts](${{ env.url }}). 🚀" >> ./pr/comment

      - name: Generate PR comment if happening other conditions
        if: ${{ needs.build.result != 'success' }}
        env:
          url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}#annotations
        run: |
          printf "Oops, The build workflow has failed! See in " >> ./pr/comment
          printf "[summary](${{ env.url }}). 😥" >> ./pr/comment

      - name: Upload the PR information
        uses: actions/upload-artifact@v2.2.2
        with:
          name: pr
          path: pr/
